[package]
name = "rash"
version = "0.1.0"
edition = "2021"
authors = ["Luke Elliot <lukejelliot25@gmail.com>"]

[lib]
path = "src/lib.rs"

[dependencies]
libc = "0.2"
lazy_static = "1.4"
thiserror = "1.0.38"